#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Techdays.Android.Resource", IsApplication=true)]

namespace Techdays.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues ();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int MvxDropDownItemTemplate = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int MvxHttpSource = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxItemTemplate = 2130771969;
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int black = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int grey = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int icongrey = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int lightgrey = 2130968579;
			
			// aapt resource value: 0x7f040007
			public const int listseparator = 2130968583;
			
			// aapt resource value: 0x7f040002
			public const int mainText = 2130968578;
			
			// aapt resource value: 0x7f040008
			public const int orange = 2130968584;
			
			// aapt resource value: 0x7f040000
			public const int transparent = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int white = 2130968581;
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int blue_button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int darkblue_button = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int green_button = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int logo = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int monoandroidsplash = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int orange_button = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int programicon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int purple_button = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int red_button = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int speakers_icon = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int yellow_button = 2130837515;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050009
			public const int AgendaImageView = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int BookImageView = 2131034120;
			
			// aapt resource value: 0x7f05000f
			public const int ContentTextView = 2131034127;
			
			// aapt resource value: 0x7f050002
			public const int LinkImageView = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int MvxBindableListItemTagUnique = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int MvxBindingTagUnique = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int MyButton = 2131034115;
			
			// aapt resource value: 0x7f05000e
			public const int NameTextView = 2131034126;
			
			// aapt resource value: 0x7f050007
			public const int RoomTextView = 2131034119;
			
			// aapt resource value: 0x7f05000c
			public const int SpeakerImageView = 2131034124;
			
			// aapt resource value: 0x7f050006
			public const int SpeakerTextView = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int TitleTextView = 2131034117;
			
			// aapt resource value: 0x7f05000d
			public const int TwitterImageView = 2131034125;
			
			// aapt resource value: 0x7f05000a
			public const int listviewArticle = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int listviewSpeakers = 2131034123;
			
			// aapt resource value: 0x7f050004
			public const int map = 2131034116;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Home_listitem_link = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Home_listitem_topic = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Home_Page_HomeView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Home_TabPage_MyAgenda = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Home_TabPage_Overview = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Home_TabPage_TopicList = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Home_TabPage_Tweets = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Main = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int monoandroidsplash = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int PracticalInfo_Page = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Sessions_item_session = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Sessions_item_timeslot = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Sessions_Page_SessionDetail = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Sessions_Page_SessionHome = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int Sessions_TabPage_SessionList = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int speaker_listitem = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int Speaker_Page_SpeakerDetail = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int Speaker_Page_SpeakerList = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int Speaker_TabPage_Bio = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int Speaker_TabPage_Sessions = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int SplashScreen = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int tweet_item = 2130903061;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070003
			public const int Mono_Android_Theme_Splash = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int MyButton = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int MyTabWidget = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int button_text = 2131165185;
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBindableListView = new int[] {
					2130771969,
					2130771970};
			
			// aapt resource value: 1
			public const int MvxBindableListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxBindableListView_MvxItemTemplate = 0;
			
			public static int[] MvxBinding = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			public static int[] MvxHttpImageView = new int[] {
					2130771971};
			
			// aapt resource value: 0
			public const int MvxHttpImageView_MvxHttpSource = 0;
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
